apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-python
  name: hello-python
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
        - image: awsm1123/hello-python:1.1.0
          imagePullPolicy: IfNotPresent
          name: hello-python
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
